// <auto-generated />
using ExamWed_DuongTruongPhuocThinh.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamWed_DuongTruongPhuocThinh.Migrations
{
    partial class SeedData
    {

    }
}
